name: Build and deploy page

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build react app
      env:
        REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      run: |
        npm ci
        npm run build
  
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: 'github-pages'
        path: build
  
    - name: Upload to github-pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: ${{ github.sha }}
        
    # - name: Deploy
    #   run: |
    #     git config --global user.name $user_name
    #     git config --global user.email $user_email
    #     git remote set-url origin https://${github_token}@github.com/${repository}
    #     npm run deploy
    #   env:
    #     user_name: 'github-actions[bot]'
    #     user_email: 'github-actions[bot]@users.noreply.github.com'
    #     github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
    #     repository: ${{ github.repository }}
